sudo: false
language: ruby
rvm:
  - 2.3
before_install: gem install bundler -v 1.15.1
script:
  - |
    rc=0;
    for sha1 in $(git log --format=format:%H ${TRAVIS_COMMIT_RANGE}); do
      echo $sha1;
      git log --format=%B -n 1 $sha1;
      bundle exec rubocop-git "${sha1}~1";
      if (( $? != 0 )); then rc=1; fi;
      echo -e "\n\n\n";
    done;
    exit $rc;
  - bundle exec rake
